server:
  port: 9527 #端口
spring:
  application:
    name: gateway #服务名称
  cloud: #配置SpringCloudGateway的路由
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心创建动态路由的功能，利用微服名进行路由

      #路由可以配多个 [路由由这几个条件组成:路由id、路由到微服务的url、断言(判断条件)]
      routes:  #路由：http://localhost:8080/ + Path,组成消费者的访问路径
       - id: consumer_routh             # 保持唯一
         uri: lb://consumer-service   # lb：根据微服务名称从注册中心获取服务请求路径
         predicates:
            - Path=/feignconsumer/**    #断言,路径相匹配的进行路由

       - id: provider_routh             # 保持唯一
         uri: lb://provider-service   # lb：根据微服务名称从注册中心获取服务请求路径
         predicates:
            - Path=/user/findById/**    #路由匹配规则：断言,路径相匹配的进行路由

# 配置eureka
eureka:
  instance:
    hostname: gateway-server
  client:
    service-url:
      registry-with-eureka: true
      fetch-registry: true
      #设置与Eureka Server交互的地址,用于查询服务和注册服务
      defaultZone: http://eureka8761.com:8761/eureka/, http://eureka8762.com:8762/eureka/


