server:
   port: 8761

# 配置注册中心
eureka:
   instance:
     hostname: eureka8761.com
   client:
    register-with-eureka: false  #是否将自己注册到注册中心
    fetch-registry: false        #是否从eureka中获取注册信息
    service-url:                 #配置暴露给Eureka Client的请求地址
     # defaultZone: http://eureka8762.com:8762/eureka/  #集群版
       defaultZone: http://localhost:8761/eureka      #单机版

   server:
     enable-self-preservation: false      #关闭自我保护
     eviction-interval-timer-in-ms: 4000  #剔除服务间隔


