server:
   port: 8762

# 配置注册中心
eureka:
   instance:
     hostname: eureka8762.com
   client:
    register-with-eureka: false  #是否将自己注册到注册中心
    fetch-registry: false        #是否从eureka中获取注册信息
    service-url:                 #配置暴露给Eureka Client的请求地址
      defaultZone: http://eureka8761.com:8761/eureka/
                  #http://127.0.0.1:8761/eureka/

   server:
     enable-self-preservation: false      #关闭自我保护
     eviction-interval-timer-in-ms: 4000  #剔除服务间隔

